name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1.0.7
        with:
          version: nightly

      - name: Install node
        uses: actions/setup-node@v2

      - name: Clone repo with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install pnpm
        run: npm install --location=global pnpm

      - name: Install dependencies
        run: make deps

      - name: Show Foundry config
        run: forge config

      - name: Check contracts are linted
        run: make lintcheck

      - name: Run tests
        run: make test
